/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-02-15 06:48:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.util.MasterModel;
import com.util.UserAccountModel;
import java.util.Date;
import com.util.ConnectionManager;
import com.util.StringHelper;
import com.util.UserModel;
import com.util.ServerConstants;
import java.util.ArrayList;
import java.util.List;
import com.util.ServerConstants;
import com.util.UserAccountModel;

public final class driverreport_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/displaytag-12.tld", Long.valueOf(1399753273477L));
    _jspx_dependants.put("/pages/./tiles/menu.jsp", Long.valueOf(1487141218978L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass.release();
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.release();
    _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>OBD Driver Report</title>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/theme/looks.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/theme/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/jquery.autocomplete-1.1.3/jquery-1.7.2.js\"></script>\r\n");
      out.write("</head>  \r\n");
      out.write("<body>   \r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\" style=\"text-align: center;\"> \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t<div id=\"welcome\">\r\n");
      out.write("\t\t<h2 class=\"title\"><a href=\"#\">Welcome to ");
      out.print(ServerConstants.APPLICATION_HEAD);
      out.write("</a></h2>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");

Object o=session.getAttribute("USER_MODEL");
UserAccountModel um=null;
if(o==null){
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}else{
	um=(UserAccountModel)o;
}
boolean isAdmin=false;
if(um.getRole()== ServerConstants.ROLE_ADMIN){ 
	isAdmin=true;
}


      out.write("\r\n");
      out.write("<h2>Welcome ");
      out.print(um.getFullname() );
      out.write("</h2>   \r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
if(isAdmin){ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addownervehicle.jsp\">Add/Delete Owner</a>&nbsp;&nbsp;&nbsp;\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addownervehicle.jsp\">Edit Details</a>&nbsp;&nbsp;&nbsp;\r\n");
} 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addalert.jsp\">Add/Delete Alerts</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/vehicle.jsp\">Live Data</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driverperformance.jsp\">Driver Performance</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/vehiclereport.jsp\"><span><span>Vehicle Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driverreport.jsp\" ><span><span>Driver Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driver_behaviour_report.jsp\" ><span><span>Driver Behaviour Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/upload.jsp\" ><span><span>Upload File</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/map.jsp?sfacility=12\" ><span><span>View Map</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<!-- style=\"background-color: yellow;\" -->\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\">Logout</a>");
      out.write("   \r\n");
      out.write("\t\t<div class=\"entry\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					String uid = StringHelper.n2s(((UserAccountModel) session
									.getAttribute("USER_MODEL")).getUserid());
							String month = StringHelper.n2s(request.getParameter("month"));
							String year = StringHelper.n2s(request.getParameter("year"));
							String severe = StringHelper.n2s(request.getParameter("severe"));
							List list= new ArrayList<com.util.MasterModel>();   
							List list1=new ArrayList<MasterModel>();
							if (month != "" && year != "" && severe != "") {		
								list= ConnectionManager.getDriverReport(month, year, severe, uid); 
							} else if (month == "" && year != "" && severe != ""){
								list = ConnectionManager.getDriverReport(month, year, severe, uid);		
							}
							
							if(list.size()>0){
								session.setAttribute("DRIVER_REPORT", list);
							}else{
								session.removeAttribute("DRIVER_REPORT");
							}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div id=\"two-columns\">\r\n");
      out.write("\t\t<!-- for viewing vehicle details -->\r\n");
      out.write("\t\t\t<div id=\"popup_box\"\r\n");
      out.write("\t\t\t\tstyle=\"width: 550px; height: 350px; overflow-y: scroll;display: none;\">\r\n");
      out.write("\t\t\t\t<!-- OUR PopupBox DIV-->\r\n");
      out.write("\t\t\t\t<span id=\"popup_text\">View Driver Details</span> <a id=\"popupBoxClose\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/theme/images/Close Button.png\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"two-columns\">\r\n");
      out.write("\t\t\t\t<center>\r\n");
      out.write("\t\t\t\t<form name=\"myform\" id=\"myform\">\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<h2>Vehicles Details</h2>\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><strong>Select :</strong></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"severe\" id=\"severe\" size=\"3\" title=\"Select severity\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">Select Behavior</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"efficient\">Efficient</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"less efficient\">Less Efficient</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"rash\">Rash</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><select name=\"month\" id=\"month\" size=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Select month\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">Select month</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"all\" >All</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">January</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">February</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"3\">March</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"4\">April</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"5\">May</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"6\">June</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"7\">July</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"8\">August</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"9\">September</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"10\">October</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"11\">November</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"12\">December</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select name=\"year\" id=\"year\" size=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle=\"Select year\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\" selected=\"selected\">Select year</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"all\" >All</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										Date date = new Date();
																	for (int i = 2012; i <= (1900 + date.getYear()); i++) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><button class=\"Button\" type=\"button\" name=\"next\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"document.forms[0].submit();\" /> <span class=\"btn\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"height: 30px; width: 150px; font-weight: bold; font-size: 15\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"t\">Show</span> <span class=\"r\"><span></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"l\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br></br>\r\n");
      out.write("\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");

																if (list.size() > 0) {
																	com.util.MasterModel mm1=	((com.util.MasterModel)list.get(0));
																
															
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div style=\"width: 98%; text-align: left;\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      //  display:table
      org.displaytag.tags.TableTag _jspx_th_display_005ftable_005f0 = (org.displaytag.tags.TableTag) _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass.get(org.displaytag.tags.TableTag.class);
      _jspx_th_display_005ftable_005f0.setPageContext(_jspx_page_context);
      _jspx_th_display_005ftable_005f0.setParent(null);
      // /pages/driverreport.jsp(132,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setName("sessionScope.DRIVER_REPORT");
      // /pages/driverreport.jsp(132,7) name = class type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setClass("hovertable");
      // /pages/driverreport.jsp(132,7) name = requestURI type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setRequestURI("/pages/driverreport.jsp");
      // /pages/driverreport.jsp(132,7) name = id type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setUid("driverRuleId");
      // /pages/driverreport.jsp(132,7) name = pagesize type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setPagesize(4);
      // /pages/driverreport.jsp(132,7) name = style type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setStyle(" width:100%;");
      // /pages/driverreport.jsp(132,7) name = defaultsort type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setDefaultsort(1);
      // /pages/driverreport.jsp(132,7) name = defaultorder type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setDefaultorder("ascending");
      // /pages/driverreport.jsp(132,7) name = export type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setExport(true);
      // /pages/driverreport.jsp(132,7) name = sort type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_display_005ftable_005f0.setSort("list");
      int _jspx_eval_display_005ftable_005f0 = _jspx_th_display_005ftable_005f0.doStartTag();
      if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        java.lang.Object driverRuleId = null;
        java.lang.Integer driverRuleId_rowNum = null;
        if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_display_005ftable_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_display_005ftable_005f0.doInitBody();
        }
        driverRuleId = (java.lang.Object) _jspx_page_context.findAttribute("driverRuleId");
        driverRuleId_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("driverRuleId_rowNum");
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");

														String vehicleId="";
														com.util.MasterModel mm=null;
														try{
															mm=((com.util.MasterModel) pageContext.getAttribute("driverRuleId"));
												
														}catch(Exception e){
															e.printStackTrace();
														}
														
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_display_005fsetProperty_005f0(_jspx_th_display_005ftable_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_display_005fsetProperty_005f1(_jspx_th_display_005ftable_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_display_005fsetProperty_005f2(_jspx_th_display_005ftable_005f0, _jspx_page_context))
            return;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<!--  vehicleId, fullname, drivername, vehicleno -->\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          //  display:column
          org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f0 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.get(org.displaytag.tags.ColumnTag.class);
          _jspx_th_display_005fcolumn_005f0.setPageContext(_jspx_page_context);
          _jspx_th_display_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
          // /pages/driverreport.jsp(153,8) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f0.setTitle("Sr.No");
          // /pages/driverreport.jsp(153,8) name = sortable type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f0.setSortable(true);
          int _jspx_eval_display_005fcolumn_005f0 = _jspx_th_display_005fcolumn_005f0.doStartTag();
          if (_jspx_eval_display_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_display_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_display_005fcolumn_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_display_005fcolumn_005f0.doInitBody();
            }
            do {
              out.print(pageContext.getAttribute("driverRuleId_rowNum"));
              int evalDoAfterBody = _jspx_th_display_005fcolumn_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_display_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_display_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f0);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          //  display:column
          org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f1 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.get(org.displaytag.tags.ColumnTag.class);
          _jspx_th_display_005fcolumn_005f1.setPageContext(_jspx_page_context);
          _jspx_th_display_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
          // /pages/driverreport.jsp(154,8) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f1.setTitle("Vehicle No");
          // /pages/driverreport.jsp(154,8) name = sortable type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f1.setSortable(true);
          int _jspx_eval_display_005fcolumn_005f1 = _jspx_th_display_005fcolumn_005f1.doStartTag();
          if (_jspx_eval_display_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_display_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_display_005fcolumn_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_display_005fcolumn_005f1.doInitBody();
            }
            do {
              out.print(mm.getVehicleno());
              int evalDoAfterBody = _jspx_th_display_005fcolumn_005f1.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_display_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_display_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f1);
            return;
          }
          _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f1);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          //  display:column
          org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f2 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.get(org.displaytag.tags.ColumnTag.class);
          _jspx_th_display_005fcolumn_005f2.setPageContext(_jspx_page_context);
          _jspx_th_display_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
          // /pages/driverreport.jsp(155,8) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f2.setTitle("Driver Name");
          // /pages/driverreport.jsp(155,8) name = sortable type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f2.setSortable(true);
          int _jspx_eval_display_005fcolumn_005f2 = _jspx_th_display_005fcolumn_005f2.doStartTag();
          if (_jspx_eval_display_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_display_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_display_005fcolumn_005f2.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_display_005fcolumn_005f2.doInitBody();
            }
            do {
              out.print(mm.getDrivername() );
              int evalDoAfterBody = _jspx_th_display_005fcolumn_005f2.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_display_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_display_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f2);
            return;
          }
          _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable.reuse(_jspx_th_display_005fcolumn_005f2);
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          //  display:column
          org.displaytag.tags.ColumnTag _jspx_th_display_005fcolumn_005f3 = (org.displaytag.tags.ColumnTag) _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia.get(org.displaytag.tags.ColumnTag.class);
          _jspx_th_display_005fcolumn_005f3.setPageContext(_jspx_page_context);
          _jspx_th_display_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
          // /pages/driverreport.jsp(157,8) name = title type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f3.setTitle("View Details");
          // /pages/driverreport.jsp(157,8) name = sortable type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f3.setSortable(true);
          // /pages/driverreport.jsp(157,8) name = media type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_display_005fcolumn_005f3.setMedia("html");
          int _jspx_eval_display_005fcolumn_005f3 = _jspx_th_display_005fcolumn_005f3.doStartTag();
          if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_display_005fcolumn_005f3.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_display_005fcolumn_005f3.doInitBody();
            }
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" title=\"view details\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"fnView('");
              out.print(mm.getVehicleId() );
              out.write('\'');
              out.write(',');
              out.write('\'');
              out.print(month);
              out.write('\'');
              out.write(',');
              out.write('\'');
              out.print(year);
              out.write('\'');
              out.write(',');
              out.write('\'');
              out.print(severe);
              out.write("')\"> <img\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
              out.print(request.getContextPath());
              out.write("/theme/images/view3.png\"\r\n");
              out.write("\t\t\t\t\t\t\t\t\t\theight=\"25px\" width=\"70px\" />\r\n");
              out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_display_005fcolumn_005f3.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_display_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_display_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia.reuse(_jspx_th_display_005fcolumn_005f3);
            return;
          }
          _005fjspx_005ftagPool_005fdisplay_005fcolumn_0026_005ftitle_005fsortable_005fmedia.reuse(_jspx_th_display_005fcolumn_005f3);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_display_005ftable_005f0.doAfterBody();
          driverRuleId = (java.lang.Object) _jspx_page_context.findAttribute("driverRuleId");
          driverRuleId_rowNum = (java.lang.Integer) _jspx_page_context.findAttribute("driverRuleId_rowNum");
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_display_005ftable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_display_005ftable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass.reuse(_jspx_th_display_005ftable_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fdisplay_005ftable_0026_005fstyle_005fsort_005frequestURI_005fpagesize_005fname_005fid_005fexport_005fdefaultsort_005fdefaultorder_005fclass.reuse(_jspx_th_display_005ftable_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
}else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label style=\"font-family: verdana;font-size: 12px;color: navy;\">No Record Found....</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t</fieldset> \r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- end #page --> \r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("$(\"#severe\").val('");
      out.print(severe);
      out.write("');\r\n");
      out.write("$(\"#month\").val('");
      out.print(month);
      out.write("');\t\r\n");
      out.write("$(\"#year\").val('");
      out.print(year);
      out.write("');\r\n");
      out.write("\r\n");
      out.write("function fnView(id,month,year,severe){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t  type: \"POST\",\r\n");
      out.write("\t\t  url: \"");
      out.print(request.getContextPath());
      out.write("/pages/reportvehicleview.jsp?id=\"+ id+ \"&severe=\"+ severe+\"&month=\"+ month+ \"&year=\"+ year,\r\n");
      out.write("\t\t\t\t\tdataType : \"text\"\r\n");
      out.write("\t\t\t\t}).done(function(msg) {\r\n");
      out.write("\t\t\t$(\"#popup_text\").html(msg);\r\n");
      out.write("\t\t\t$('#popup_box').fadeIn(\"slow\");\r\n");
      out.write("\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$('#popupBoxClose').click(function() {\t\r\n");
      out.write("\t$('#popup_box').fadeOut(\"slow\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_display_005fsetProperty_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f0 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    _jspx_th_display_005fsetProperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_display_005fsetProperty_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
    // /pages/driverreport.jsp(146,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f0.setName("export.csv.filename");
    // /pages/driverreport.jsp(146,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f0.setValue("driver report.csv");
    int _jspx_eval_display_005fsetProperty_005f0 = _jspx_th_display_005fsetProperty_005f0.doStartTag();
    if (_jspx_th_display_005fsetProperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f0);
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f1 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    _jspx_th_display_005fsetProperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_display_005fsetProperty_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
    // /pages/driverreport.jsp(148,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f1.setName("export.xml.filename");
    // /pages/driverreport.jsp(148,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f1.setValue("driver report.xml");
    int _jspx_eval_display_005fsetProperty_005f1 = _jspx_th_display_005fsetProperty_005f1.doStartTag();
    if (_jspx_th_display_005fsetProperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f1);
    return false;
  }

  private boolean _jspx_meth_display_005fsetProperty_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_display_005ftable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  display:setProperty
    org.displaytag.tags.SetPropertyTag _jspx_th_display_005fsetProperty_005f2 = (org.displaytag.tags.SetPropertyTag) _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.get(org.displaytag.tags.SetPropertyTag.class);
    _jspx_th_display_005fsetProperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_display_005fsetProperty_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_display_005ftable_005f0);
    // /pages/driverreport.jsp(150,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f2.setName("export.csv.filename");
    // /pages/driverreport.jsp(150,8) name = value type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_display_005fsetProperty_005f2.setValue("driver report.xls");
    int _jspx_eval_display_005fsetProperty_005f2 = _jspx_th_display_005fsetProperty_005f2.doStartTag();
    if (_jspx_th_display_005fsetProperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fdisplay_005fsetProperty_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_display_005fsetProperty_005f2);
    return false;
  }
}
