/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2016-03-08 12:27:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.util.VehicleModel;
import java.util.Iterator;
import com.util.ServerConstants;
import com.util.DatabaseUtility;
import com.util.StringHelper;
import com.util.MasterModel;
import com.util.ConnectionManager;
import java.util.List;
import com.util.ServerConstants;
import com.util.UserAccountModel;

public final class map_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/pages/./tiles/menu.jsp", Long.valueOf(1456917104370L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/theme/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/jquery.autocomplete-1.1.3/jquery-1.7.2.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("    src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body >\r\n");
      out.write("<div id=\"wrapper\" style=\"text-align: center;\"> \r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t<div id=\"welcome\">\r\n");
      out.write("<form action=\"\">\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

Object o=session.getAttribute("USER_MODEL");
UserAccountModel um=null;
if(o==null){
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}else{
	um=(UserAccountModel)o;
}
boolean isAdmin=false;
if(um.getRole()== ServerConstants.ROLE_ADMIN){ 
	isAdmin=true;
}


      out.write("\r\n");
      out.write("<h2>Welcome ");
      out.print(um.getFullname() );
      out.write("</h2>   \r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
if(isAdmin){ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addownervehicle.jsp\">Add/Delete Owner</a>&nbsp;&nbsp;&nbsp;\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addownervehicle.jsp\">Edit Details</a>&nbsp;&nbsp;&nbsp;\r\n");
} 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addalert.jsp\">Add/Delete Alerts</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/vehicle.jsp\">Live Data</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driverperformance.jsp\">Driver Performance</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/vehiclereport.jsp\"><span><span>Vehicle Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driverreport.jsp\"  style=\"background-color: yellow;\"><span><span>Driver Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/driver_behaviour_report.jsp\" style=\"background-color: yellow;\"><span><span>Driver Behaviour Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/upload.jsp\" style=\"background-color: yellow;\"><span><span>Upload File</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/map.jsp?sfacility=12\" style=\"background-color: yellow;\"><span><span>View Map</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\">Logout</a>");
      out.write("   \r\n");

double lat=0;  
double lng=0;
int  vid=StringHelper.n2i((request.getParameter("vehicleNo"))) ;
if(vid>0){
System.out.println("vehicle id"+vid);
String query="SELECT  latsend, lngsend,  obdid FROM `obdserver` where vehicleid='"+vid+"'order by obdid asc limit 1;";
List l=ConnectionManager.getBeanList(MasterModel.class, query);
MasterModel mm=(MasterModel)l.get(0);
lat=StringHelper.n2d(mm.getLatsend());
lng=StringHelper.n2d(mm.getLngsend());
}

      out.write("\r\n");
      out.write("<div class=\"entry\">\r\n");

      out.write('\r');
      out.write('\n');

	List vehicleList = DatabaseUtility.getBeanList(
  				com.util.VehicleModel.class,
  				ServerConstants.QUERY_VEHICLES_DETAILS2,
  				new Object[]{});
  		
      out.write("  \r\n");
      out.write("  \t\t<BR><BR>\r\n");
      out.write("  \t\tSelect Vehicle &nbsp;&nbsp;\t<select name=\"vehicleNo\" id=\"vehicleNo\"  onchange=\"document.forms[0].submit();\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle=\"vehicleNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"0\">Select</option>\r\n");
      out.write("  \t\t");

  		for (Iterator iterator = vehicleList.iterator(); iterator.hasNext();) {
  			VehicleModel vm =  (VehicleModel) iterator.next();
 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("<option value=\"");
      out.print(vm.getVehicleId());
      out.write('"');
      out.write('>');
      out.print(vm.getDrivername());
      out.write('-');
      out.print(vm.getVehicleno() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("</select>\r\n");
      out.write("\t\t\t\t<div id=\"map\" style=\"height:500px; width:1000px\"></div>  \r\n");
      out.write("<div style=\"padding-left: 300px;\" ><input type=\"button\" value=\"Display\" onclick=\"fnview('");
      out.print(lat);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(lng);
      out.write("')\"> </div>  \r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t</div></div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function fnview(lats,lngs) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar lt=Number(lats);\r\n");
      out.write("\tvar ln=Number(lngs);\r\n");
      out.write("\t  //var myLatLng = {lat: 18.5073958, lng: 73.7871018};\r\n");
      out.write("\t  var myLatLng = {lat: lt, lng: ln};  \r\n");
      out.write("\r\n");
      out.write("\t  var map = new google.maps.Map(document.getElementById('map'),{\r\n");
      out.write("\t    zoom:16,\r\n");
      out.write("\t    center: myLatLng\r\n");
      out.write("\t  });\r\n");
      out.write("\r\n");
      out.write("\t  var marker = new google.maps.Marker({\r\n");
      out.write("\t    position: myLatLng,\r\n");
      out.write("\t    map: map,\r\n");
      out.write("\t    title: 'Hello World!'\r\n");
      out.write("\t  });\r\n");
      out.write("\t}\r\n");
      out.write("fnview('");
      out.print(lat);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(lng);
      out.write("');\r\n");
      out.write("document.getElementById('vehicleNo').value='");
      out.print(vid);
      out.write("';\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
