/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-01-27 05:17:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.util.ServerConstants;
import com.util.UserAccountModel;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Object o=session.getAttribute("USER_MODEL");
UserAccountModel um=null;
if(o==null){
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}else{
	um=(UserAccountModel)o;
}
boolean isAdmin=false;
if(um.getRole()== ServerConstants.ROLE_ADMIN){ 
	isAdmin=true;
}


      out.write("\r\n");
      out.write("<h2>Welcome ");
      out.print(um.getFullname() );
      out.write("</h2>   \r\n");
      out.write("<BR>\r\n");
      out.write('\r');
      out.write('\n');
if(isAdmin){ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/addownervehicle.jsp\">Add/Delete Owner</a>&nbsp;&nbsp;&nbsp;\r\n");
}else{ 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\">Edit Details</a>&nbsp;&nbsp;&nbsp;\r\n");
} 
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\">Add/Delete Alerts</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\">Live Data</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\">Driver Performance</a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\"><span><span>Vehicle Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\" ><span><span>Driver Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\" ><span><span>Driver Behaviour Report</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("#\" ><span><span>Upload File</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/map.jsp?sfacility=12\" ><span><span>View Map</span></span></a>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("<!-- style=\"background-color: yellow;\" -->\r\n");
      out.write("<a href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\">Logout</a>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
