/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2017-02-15 06:48:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.tiles;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import java.io.IOException;
import org.jfree.chart.ChartUtilities;
import org.jfree.data.xy.XYDataset;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartFactory;
import com.util.LineChart2D;
import com.util.OwnerInfoModel;
import com.util.ConnectionManager;
import com.util.StringHelper;
import java.sql.Connection;
import java.util.StringTokenizer;
import java.io.PrintWriter;
import java.util.Set;
import java.util.HashMap;
import java.util.Enumeration;
import org.apache.commons.collections.functors.ForClosure;
import java.net.URLDecoder;
import java.net.URL;
import java.util.Iterator;
import java.util.List;
import com.util.DBUtils;
import org.json.JSONTokener;
import org.json.JSONObject;

public final class save_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String method = StringHelper.n2s(request.getParameter("method"));
	String id = StringHelper.n2s(request.getParameter("id"));
	System.out.println(method + " " + id);
	
	final java.util.HashMap parameters = StringHelper.displayRequest(request);
	String str = "";

	if (method.equalsIgnoreCase("getDomain")) {
		System.out.println("Into getDomain");
		str = ConnectionManager.getDomain();
		response.getWriter().write(str);
		response.getWriter().close();
	}
	else if (method.equalsIgnoreCase("logout")) {
session.removeAttribute("USER_MODEL");
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\twindow.location.href='");
      out.print(request.getContextPath());
      out.write("/pages/index.jsp';\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

	}
	
	else if(method.equalsIgnoreCase("addAlert")){
	String ownerid = StringHelper.n2s(request.getParameter("ownerid"));
	String type= StringHelper.n2s(request.getParameter("type"));
	String val= StringHelper.n2s(request.getParameter("val"));
	String vehicelId= StringHelper.n2s(request.getParameter("vehicelId"));
	
	boolean b = ConnectionManager.setAlert(ownerid, type, val,vehicelId);
	if(b){   
		out.println("Alert Added In Database!");
	}
	else{
		out.println("Error in Adding Alert In Database!");
	}
	}
	
	
	else if(method.equalsIgnoreCase("addOwner")){
		String ownerid = StringHelper.n2s(request.getParameter("ownerid"));
		String drivername= StringHelper.n2s(request.getParameter("drivername"));
		String vno= StringHelper.n2s(request.getParameter("vno"));
		String imei= StringHelper.n2s(request.getParameter("imei"));
		
		boolean b = ConnectionManager.addOwner(ownerid, drivername, vno, imei);
		if(b){
			out.println("Vehicle Details Added In Database!");
		}
		else{
			out.println("Error in Adding Vehicle Details In Database!");
		}
	
	
	}else if(method.equalsIgnoreCase("createNewUser")){
		
		
		boolean b = ConnectionManager.createNewUser(parameters);
		if(b){
			out.println("User has been registered");
		}
		else{
			out.println("Error adding user details!");
		}
	
	
	}
	
	
	else if(method.equalsIgnoreCase("deleteDriver")){
		String ownerid = StringHelper.n2s(request.getParameter("ownerid"));
		String vehicleid = StringHelper.n2s(request.getParameter("vehicleid"));
		boolean b =ConnectionManager.deleteDriver(vehicleid);
	
		if(b){
			out.println("Driver Details Deleted From Database!");
		}
		else{
			out.println("Error in Deleting Database!");
		}
		
	
	
	
	}else if(method.equalsIgnoreCase("deleteVehicle")){
		String vehicleId = StringHelper.n2s(request.getParameter("vehicleId"));
		String qu="delete from vehicles where vehicleId="+vehicleId;
		ConnectionManager.executeUpdate(qu);
	}else if(method.equalsIgnoreCase("updateContact")){
		String userid = StringHelper.n2s(request.getParameter("userid"));
		String phoneno = StringHelper.n2s(request.getParameter("phoneno"));
		String qu="update useraccounts set phoneno='"+phoneno+"' where userid="+userid;
		ConnectionManager.executeUpdate(qu);
	}
	
	
	else if(method.equalsIgnoreCase("deleteAlert")){
		String ownerid = StringHelper.n2s(request.getParameter("alertid"));
		
String qu="delete from alerts where alertId="+ownerid;
ConnectionManager.executeUpdate(qu);
	
	}
	
	else if(method.equalsIgnoreCase("delUser")){
		String ownerid = StringHelper.n2s(request.getParameter("ownerid"));
		boolean b = ConnectionManager.delOwner(ownerid);
		if(b){
			out.println("User Details Deleted From Database!");
		}
		else{
			out.println("Error in Deleting Database!");
		}
	}	else if(method.equalsIgnoreCase("generateDriverPerformance")){
		List list =(List)session.getAttribute("LIST2");
		
		 XYDataset pop = LineChart2D.createDataset2(list);
		  
		  JFreeChart chart = ChartFactory.createTimeSeriesChart(
		  "Driver Performance Graph",
		  "Date",
		  "VechicleSpeed",
		  pop,
		  true,
		  true,   
		  false);
		  
		  XYPlot plot = (XYPlot)chart.getPlot();
	       
	        final XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
	        renderer.setSeriesLinesVisible(0, true);
	        renderer.setSeriesShapesVisible(1, true);
	        renderer.setSeriesShapesVisible(2, true);
	        plot.setRenderer(renderer);

	      
	        
		  ValueAxis xAxis =(ValueAxis) plot.getDomainAxis();
		  xAxis.setVerticalTickLabels(true);
		  xAxis.setTickLabelsVisible(true);
		  try {
			  ChartUtilities.writeChartAsPNG(response.getOutputStream(), chart, 1000, 500);
		//  ChartUtilities.saveChartAsJPEG(new File("D:\\chart.jpg"), chart, 500, 300);
		  } catch (IOException e) {   
		  System.err.println("Problem occurred creating chart.");
		  }
		  return;
		  
	}
	
	
	else if (method.equalsIgnoreCase("send")) {

				String iat = StringHelper.nullObjectToStringEmpty(parameters
						.get("iat"));
				String maf = StringHelper.nullObjectToStringEmpty(parameters
						.get("maf"));
				String throttlepos = StringHelper
						.nullObjectToStringEmpty(parameters.get("throttlepos"));
				
				String load_pct = StringHelper.nullObjectToStringEmpty(parameters.get("load_pct"));
				String vss = StringHelper.nullObjectToStringEmpty(parameters.get("vss"));
				String rpm = StringHelper.nullObjectToStringEmpty(parameters.get("rpm"));
				String temp = StringHelper.nullObjectToStringEmpty(parameters.get("temp"));
				String imei = StringHelper.nullObjectToStringEmpty(parameters.get("imei"));
				String latsend = StringHelper.nullObjectToStringEmpty(parameters.get("latsend"));
				String lngsend = StringHelper.nullObjectToStringEmpty(parameters.get("lngsend"));
				long time= StringHelper.n2long(parameters.get("time"));
				String dt=StringHelper.getDBDate(time);
				OwnerInfoModel oi  = ConnectionManager.getOwnerId(imei);
				String ownerid;
				String ownerno;
				if(oi!=null){
					try{
						String query = "INSERT INTO obdserver (load_pct, temp, rpm, vss, iat, maf, throttlepos, vehicleId, latsend, lngsend,timeLong,`time`)  values(?,?,?,?,?,?,?,?,?,?,?,?)";
						System.out.println(query);
						int i = ConnectionManager.executeUpdate(query, new Object[] { load_pct,temp, rpm, vss, iat, maf, throttlepos, oi.getVehicleId(), latsend, lngsend,time,dt});
						
						
						boolean b = ConnectionManager.setOBDList(load_pct, iat, maf, throttlepos, vss, rpm, temp,  latsend, lngsend,oi);
						if(b){
							System.out.println("Writing Data To Server From Client " +b);
						}else{
							System.out.println("Server Writing Error / Connection Error! \n Please Restart The Server!" +b);
						}
					}catch(Exception e){
						e.printStackTrace();
					}
					
				}
				
			
	
		response.getWriter().write("DONE");
		response.getWriter().close();
		
 
	}else if (method.equalsIgnoreCase("getVehicles")) {
		str = ConnectionManager.getVehicleList(parameters); 
		response.getWriter().write(str);
		response.getWriter().close();
	}
	
	
	
	

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
